### ISSUE TITLE
BuildQualityChecks@6 still the latest one?

### ISSUE THREAD

**Issue by PreetSangha** [MicrosoftPremier/VstsExtensions#104]
Looking at the readme, example is BuildQualityChecks@6. Can anyone confirm if that is indeed the latest one please.

Thanks Preet

**Comment by ReneSchumacher** [comment]
Hey,

sorry for pointing this out. We just forgot to update the yaml snippet in the docs. You can always see the latest version from the marketplace (see https://marketplace.visualstudio.com/items?itemName=mspremier.BuildQualityChecks) or our change notes (see https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/changeNotes.md).

The latest version is 7.2.2 with 7.3.0 about to be released.

René

**Comment by PreetSangha** [comment]
Thank you so much for the quick reply
