### ISSUE TITLE
Show Warning Statistics: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by greycoding** [MicrosoftPremier/VstsExtensions#116]
Self-hosting Azure DevOps Server 2019
TFVC
Simple build definition with NuGet Restore, Visual Studio Build - 2017 and CheckBuildQuality task.
C# Solution, ConsoleApp (.NET Framework 4.8) - will intentionally throw 2 warnings (for testing).
CheckBuildQuality: The default settings have been modified as follows:

- Warninggs Policy - Enables: checked
- Fail Build On: Fixed Threshold/Previous value (doesn't matter)
- Show warning Statistics (Obviously this setting throws the error. If the setting is deactivated, the Task runs as expected.)
- Evaluate Task Warnings (with default Tasks Filter)

Debug-Output:
Counting warnings from tasks:
    Build solution $(build.sourcesDirectory)\Solution.sln
##[debug]WarningsAnalyzer.runLogFileAnalysis
##[debug]inclusiveFiltering=false
##[debug]getTimelineLogLines
##[debug]waitForLogInformation
Waiting for log information of task 'Build solution $(build.sourcesDirectory)\Solution.sln'...
##[debug]getBuildJobRecords
##[debug]getCorrelatingJobFromTimeline
##[debug]ensureJobAndPhasPositionSet
     Running detailed task log analysis...
     Total warnings: 2, Filtered warnings: 2
##[debug]evaluateFileWarnings=false
Overall total warnings: 2
Overall filtered warnings: 2
##[debug]warningFailOption=build
##[debug]NewBaselineWarningsRule.isFulfilledImpl
##[debug]NewBaselineRule.evaluateRuleCore
##[debug]CompareToBaselineWarningsRule.isFulfilledImpl
##[debug]CompareToBaselineWarningsRule.getWarningsAnalysisFromBaselineBuild
##[debug]getBaselineBuildId
##[debug]getBaselineBuild
##[debug]getCurrentJobStartTime
**Cannot read property 'toLowerCase' of null
[ERROR] Cannot read property 'toLowerCase' of null
##[error]Cannot read property 'toLowerCase' of null**
##[debug]Processed: ##vso[task.logissue type=error;]Cannot read property 'toLowerCase' of null
##[debug]setTaskResult
##[debug]Agent.TempDirectory=C:\Agents\2\_work\_temp
##[debug]Processed: ##vso[task.addattachment type=Distributedtask.Core.Summary;name=Build Quality Checks;]C:\Agents\2\_work\_temp\BuildQualityChecksSummary.md
##[debug]createBuildIssues=true
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;]
##[section]Finishing: Check build quality

**Comment by ReneSchumacher** [comment]
Hi @greycoding,

thanks for reporting this. I'll look into the error and update the issue accordingly.

**Comment by ReneSchumacher** [comment]
Hi @greycoding,

we've identified the bug and are preparing a new release with a fix. The new version should be public in about an hour. Thanks for your patience!

**Comment by greycoding** [comment]
Hi @ReneSchumacher ,

thank you, that was very quick!
