### ISSUE TITLE
Fail Build On: Force Fewer Warnings - Only works from the second build on after increasing number of warnings

### ISSUE THREAD

**Issue by greycoding** [MicrosoftPremier/VstsExtensions#117]
Self-hosting Azure DevOps Server 2019
TFVC
Simple build definition with NuGet Restore, Visual Studio Build - 2017 and CheckBuildQuality task.
C# Solution, ConsoleApp (.NET Framework 4.8)

- First Build (ID: 105659) with 2 Warnings
- Second Build with 5 Warnings (+3): **Build Quality Checks: succeeded (not expected)**
- Third Build with 5 Warnings (+0): **Build Quality Checks: failed (as expected)**

CheckBuildQuality: The default settings have been modified as follows:
Warnings Policy - Enabled: checked
Fail Build On:
    **Force Fewer Warnings: checked**
    Evaluate Task Warnings (with default Tasks Filter): checked

**Output from second build:**
SystemVssConnection exists true
Using LegacyJobResolver
Validating build warnings policy...
Running task warnings analysis...
Counting warnings from tasks:
  - Build solution $(build.sourcesDirectory)\Solution.sln
     Running generic task log analysis...
     **Total warnings: 5, Filtered warnings: 5**
Overall total warnings: 5
Overall filtered warnings: 5
Found baseline build with ID 105659.
Running task warnings analysis...
Counting warnings from tasks:
  - Build solution $(build.sourcesDirectory)\Solution.sln
     Running generic task log analysis...
     **Total warnings: 2, Filtered warnings: 2**
Overall total warnings: 2
Overall filtered warnings: 2
**[SUCCESS] Warnings policy passed with 5 warning(s).**

**Comment by ReneSchumacher** [comment]
Ouch! This is embarrassing :-( How could we miss this?! That's what you get for primarily focusing on code coverage.

The issue is already fixed and in the release pipeline. Sorry for that!

**Comment by greycoding** [comment]
Thanks, v7.5.2 now works as expected.
