### ISSUE TITLE
Cleanup doesn't use the YAML clean option

### ISSUE THREAD

**Issue by benventive** [MicrosoftPremier/VstsExtensions#119]
Hello,

When using PostBuildCleanup in YAML with Azure Pipelines, it seems that the cleanup option set in YAML (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace) is ignored in favored of the one set in the pipeline options. One easy workaround is to align the 2 options but, ideally, the YAML option should take precedence in this step, just as in the checkout step.

Thanks!

**Comment by ReneSchumacher** [comment]
Hi @benventive,

the Post Build Cleanup extension is still not really supported for YAML pipelines as those pipelines do not use the default variables of the older pipeline model. We'll need to update the task to make it compatible.

**Comment by jamers99** [comment]
@ReneSchumacher are there plans for this to be done? I really need this functionality in our YAML pipelines. It works for most, but then some random ones don't work. This is a great tool that I would love to use more!

**Comment by ReneSchumacher** [comment]
@jamers99 Sorry for not getting back to you sooner. It's currently a pretty busy time here at Microsoft. See my comment at https://github.com/MicrosoftPremier/VstsExtensions/issues/162#issuecomment-1127538576. We're now actively working on a YAML version of the task.
