### ISSUE TITLE
No html escaping in statistics

### ISSUE THREAD

**Issue by Bouke** [MicrosoftPremier/VstsExtensions#126]
Some error that's reported contains HTML (e.g. `<input />`). This is rendered like this in the extension's statistics output:

![image](https://user-images.githubusercontent.com/235882/101554215-7c77f700-39b6-11eb-839b-064fb5b62f82.png)

**Comment by ReneSchumacher** [comment]
Hi @Bouke,

that's a good catch we didn't think about. I'll make sure this is fixed with the next version.

Thanks!
René

**Comment by ReneSchumacher** [comment]
Hi @Bouke,

the new version 8.0.0 is in our release pipeline and should be available online shortly. It should properly escape HTML now. If you still see issues, please let me know.

Happy holidays,
René

**Comment by Bouke** [comment]
Works great, thanks! Happy holidays to you as well.
