### ISSUE TITLE
Getting unexpected warnings with "Build Quality Checks" task

### ISSUE THREAD

**Issue by caghand** [MicrosoftPremier/VstsExtensions#130]
Issue #10 is happening again, this time on version 8.0.1 (as compared to 8.0.0):

##[warning]Resource file haven't set, can't find loc string for key: BaselineBuild
##[warning]Resource file haven't set, can't find loc string for key: CoverageDataFound

Probably due to this latest change in 8.0.1?:
- Bump version of the azure-pipelines-task-lib to get rid of NodeJS warning `Warning: Use Cipheriv for counter mode of aes-256-ctr`

**Comment by ReneSchumacher** [comment]
Hi @caghand,

sorry for missing this issue in the last release. This is caused to a version mismatch of two libraries we're using and does not impact the task itself. You just see those strange warnings when we try to use localized strings for logging. We are already fixing the problem and a new version will be available today.

René

**Comment by ReneSchumacher** [comment]
Hi again,

we are in the process of release v8.0.2 of the Build Quality Checks extension with fixed log messages. The new version should be online in a couple minutes. I'm closing this issue now as the new version resolves it.

Sorry again for the inconvenience!
René

**Comment by caghand** [comment]
Thanks, I am seeing that it's fixed with version 8.0.2! :)
