### ISSUE TITLE
Incorrect Overview.md for BuildQualityChecks 

### ISSUE THREAD

**Issue by KatieProchilo** [MicrosoftPremier/VstsExtensions#138]
The current overview is for CreateWorkItem. Looks like an[ old commit](BuildQualityChecks/en-US/overview.md) was popped on top or something

**Comment by ReneSchumacher** [comment]
Ouch, good catch, thanks for that! That was a copy/paste error in our release pipeline so it automatically updated the wrong docs. Fixed that as well.
