### ISSUE TITLE
Create Work Item: Allow to link commits in Work Item

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftPremier/VstsExtensions#142]
I could not find on a link type that allows to link to specific commits in a repository. This would be nice. PR is possible, but not GIT commits.

**Comment by ReneSchumacher** [comment]
Hi @SebastianSchuetze,

can you provide more information on the use case? Are you looking for a way to specify a commit hash (or multiple) to link the work item to? Or would you like to link the work item to the commit that triggered the pipeline?

**Comment by SebastianSchuetze** [comment]
I would rather be able to define what exact commit I want to link to the work item. 
Meaning, give
* project
* repo
* branch
* commit
And add this link to the "Development" section of the work item. If this is included then you can easily also link the current commit in your build by yourself. But I am more interested in linking the commit I like to choose.

**Comment by ReneSchumacher** [comment]
Got it.

I'm still wondering, though, what the use case behind linking an arbitrary commit is? While we could add options to specify target project, repo and commit hash (there's no need to provide the branch), the task's ability to link to that commit depends on your security settings for pipelines. (i.e., it'll always work for the current project, but might not work for other projects).

**Comment by SebastianSchuetze** [comment]
We have a use case. In our company as the team operating azure devops services we are required to scan all repositories for secrets once a week. When we have a find. We would like to create a bug which links directly to the commit containing the secret.

This makes it easier for users to spot it and working the a full tracible link in the created bug.

**Comment by ReneSchumacher** [comment]
Alright, that seems like a valuable use case. I've put that on the backlog and see how quickly we can get this done. We'll probably add a multiline parameter (similar to additional fields) that supports linking multiple commits and/or change sets.

**Comment by SebastianSchuetze** [comment]
Any update when you think this could be implemented?

**Comment by ReneSchumacher** [comment]
Sorry, I couldn't find the time prior to my vacation. I'm starting with the implementation (among other things) today.

**Comment by ReneSchumacher** [comment]
Hi @SebastianSchuetze,

sorry for the delay. Our internal review process took longer than I expected. The new version is being released right now and should be published to the marketplace within the hour. There is a new option to link the work item to code, which allows linking one or more commits and/or changesets. Let me know if it meets your needs.

**Comment by ReneSchumacher** [comment]
I'm closing this issue now as it should be resolved. If you believe there's more to do from our side, please add new comments or create a new issue.
