### ISSUE TITLE
Show the new warnings in the "Build Quality Checks" task

### ISSUE THREAD

**Issue by SamTh3D3v** [MicrosoftPremier/VstsExtensions#143]
I am using "[Build Quality Checks](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)" task to check if the warning counts has increased in a build compared to a previous one.

The task return a summarized report showing the warning count (and fails if the warnings increased!), something like:
> Total warnings: 22, Filtered warnings: 22

**Question**
Is there a way to show the new warnings in the new build? Currently, I have to go through the previous build and manually compare its warnings with the warnings in the new build in order to identify the new ones! This is a really tedious task, is there a built in way that automates that and show only the new warnings in the report?

Thanks!

**Comment by ReneSchumacher** [comment]
Hi @SamTh3D3v,

sorry for the late response. You can enable the warning statistics option. This generates more detailed information about the warnings that have been added or removed.

**Comment by SamTh3D3v** [comment]
Hi @ReneSchumacher, 

No worries at all, I appreciate you taking the time to look into this!

Yes, the stat option is enabled in the task: 

![image](https://user-images.githubusercontent.com/2827220/116797145-c2a73180-aae2-11eb-8eb4-4f35226fbeaf.png)

That's the kind of output I am getting from the task:

![image](https://user-images.githubusercontent.com/2827220/116797192-452ff100-aae3-11eb-8cef-071c9f74fc36.png)

The build solution task, does log the warnings in the vso format and all:

![image](https://user-images.githubusercontent.com/2827220/116797211-790b1680-aae3-11eb-9680-f135213cb5ee.png)

Any thoughts pls?

**Comment by ReneSchumacher** [comment]
The statistics are not in the log. There is a section called "Extensions" in the pipeline summary view, and you will find the statistics there.

**Comment by ReneSchumacher** [comment]
Btw: I'd recommend updating to the latest version of the Build Quality Checks task. It has a couple improvements and bug fixes, and I believe the statistics are way better on the newer versions.

**Comment by SamTh3D3v** [comment]
Oh I see, my bad I was looking in the wrong location!
But, still the output doesn't look that helpful, will the update fix that?

![image](https://user-images.githubusercontent.com/2827220/116797667-8f67a100-aae8-11eb-8671-7c17a21ef628.png)

**Comment by ReneSchumacher** [comment]
Yes, it will. We added more details with version 7.4.0 if I remember correctly. It'll give you the exact warnings that have changed. It at least we try to 😉 Since the task only has limited context for each warning, we use a heuristic to find the changes. So far, I haven't heard any complaints, though.

**Comment by SamTh3D3v** [comment]
I appreciate your help, thank you ^^.
