### ISSUE TITLE
TF401320: Rule Error for field Environment. Error code: Required, HasValues, LimitedToValues, AllowsOldValue, InvalidEmpty.

### ISSUE THREAD

**Issue by TiggySravan** [MicrosoftPremier/VstsExtensions#149]
Trying to create the Bug upon the failure of the previous Task and I am getting this issue. Please help me out
![image](https://user-images.githubusercontent.com/44838166/126177884-d9c18cf3-174a-449f-88ea-0f651b5416c8.png)

**Comment by ReneSchumacher** [comment]
Hi @TiggySravan,

looks like you didn't set a required field (*Environment*) in your work item. Or you tried to set an invalid value. The error says that the field is required and only supports certain values. The task cannot create work items that don't meet all requirements set by work item rules.

**Comment by TiggySravan** [comment]
Hi @ReneSchumacher 
Thanks for reaching out to me. Could you please help me in understanding where should I set the field for the environment?
In the task I don't see the option to do so? Is it something that can be done explicitly? Please help me out

**Comment by ReneSchumacher** [comment]
Hi again,

are you using the task in a classic or YAML pipeline? There are only a few parameters for specific fields, mainly those that every single work item type has (title, area path, iteration path, and assigned to). All other fields must be set through the *Additional Fields* parameter (see https://github.com/MicrosoftPremier/VstsExtensions/blob/master/CreateWorkItem/en-US/overview.md#user-content-fieldmappings). If you're using a classic pipeline, you should use the custom field editor (click the three dots next to the field in the UI). It makes sure that all required fields are set and only allowed values can be specified.

**Comment by TiggySravan** [comment]
Hi
Thanks a lot @ReneSchumacher .
Adding the Additional Field Parameters in the task solved the issue and Bug been creating succesfully.

**Comment by ReneSchumacher** [comment]
Glad I could help :-) I'm closing this issue then. If you need anything else, just open a new one.
