### ISSUE TITLE
Show warnings count per solution

### ISSUE THREAD

**Issue by MikeWilliams-UK** [MicrosoftPremier/VstsExtensions#15]
In our build definition we build seven solutions hence it can be difficult to find out which of them has caused the increase in warnings.

In the phase where the this extension count the warnings it would be very useful if the count per solution was displayed.

Currently this is logged as
`
Counting warnings from tasks:
- Build solution $/Solution1.sln
- Build solution $/Solution1.sln
- Build solution $/Solution1.sln
Total warnings: 15
`

Please change to something like this
`
Counting warnings from tasks:
- Build solution $/Solution1.sln [10 warnings]
- Build solution $/Solution1.sln [2 warnings]
- Build solution $/Solution1.sln [3 warnings]
Total warnings: 15`

**Comment by ReneSchumacher** [comment]
Hi Mike,

I like the idea of adding a bit more structure to the output. Let me see what I can do over the next three hours while I'm on the train back home. If all goes well, I'll have the change ready for release tonight.

René

**Comment by ReneSchumacher** [comment]
Hi Mike,

sorry for the delay. We had another feature request (StyleCop Runner log analysis) and decided to add that one as well. The new version is currently being reviewd by my team and should be available in the marketplace tomorrow (Sept. 20).

René

**Comment by MikeWilliams-UK** [comment]
How do I update the extension in VSTS?

I can only see an options to disable it or un unstall it.

Is the only way to update via Uninstall and re-install?

**Comment by ReneSchumacher** [comment]
Hi Mike,

you don't need to manually update the extension. Azure DevOps extensions are updated automatically when a new version is published to the marketplace.

René

**Comment by MikeWilliams-UK** [comment]
Thanks, thats good to know.

**Comment by ReneSchumacher** [comment]
The new version is publishing right now. You should see it in the marketplace in a few minutes. I'm closing the issue for now. If you have any other requests or feedback, please feel free to open a new issue.

Happy building!
René
