### ISSUE TITLE
Build Quality fails with `The task did not upload its log information within the maximum wait time`

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftPremier/VstsExtensions#150]
We have a build set up which runs 2 jobs in parallel. The Build Quality task is set up to check the number of warnings. Currently it seems to be check the builds for both jobs (so I don't know what happens if one of the jobs gets delayed) but that's not necessary if it's possible to configure the task to only look within its own job.

Up until yesterday this process was working fine, but since yesterday all of the executions of the task are failing indicating some form of timeout. I've run the build in debug mode and there isn't much going on (I've attached the log for just this task where it failed in debug mode and the last time it passed, and I'm happy to send the full log over to Microsoft but would rather not post it here)

[FailBuildQuality.txt](https://github.com/MicrosoftPremier/VstsExtensions/files/6858783/FailBuildQuality.txt)
[PassBuildQuality.txt](https://github.com/MicrosoftPremier/VstsExtensions/files/6858784/PassBuildQuality.txt)

**Comment by ReneSchumacher** [comment]
Hi @MatthewSteeples,

the BQC task should only evaluate warnings from the current job and, when comparing to the previous build, also only look at previous corresponding jobs. I.e., the first job in your pipeline should only compare to the first job in the previous build, not to multiple jobs. This has been introduced in v6.2.0.

Could you run your build with both variables System.Debug and BQC.LogRawData set to true and send the full build logs to PSGerExtSupport@microsoft.com? The raw data logging should show the build timeline information, which helps me better understand what might be blocking here.

Also, it would be very good if you updated the task to the latest version. Version 6.4.4 is pretty old and might have some bugs. The latest version is 8.1.0 and getting logs from that version really simplifies the analysis. If something is blocking you from upgrading, let me know. Maybe I can help.

**Comment by MatthewSteeples** [comment]
Thanks for the response @ReneSchumacher. I hadn't realised we were running such an outdated version (keeping track of updates is a full time job in itself!) so I've updated to 8.1 now and we still get the same issue. I'm emailing the logs through to you now with a description of what the stages are

**Comment by MatthewSteeples** [comment]
Looks green now on 8.1.1

**Comment by ReneSchumacher** [comment]
Oh, wow, you already tested :-) I was about to tell you that we released the fix. Glad it worked. I'm closing the issue then. Feel free to create a new one or add more comments if the issue resurfaces.

**Comment by MatthewSteeples** [comment]
We just happened to have a build go through which I was keeping an eye on for something else and I noticed it passed. Thanks for the quick turnaround
