### ISSUE TITLE
PostBuildCleanup doesn't properly handle when multiple repos checked out

### ISSUE THREAD

**Issue by richardgavel** [MicrosoftPremier/VstsExtensions#152]
If I have multiple repos checked out and use the PostBuildCleanup with no options, I would expect it to to run a git clean on each checked out repo. Instead it just runs it on the Build.SourcesDirectory, which is not itself a git repo.

##[debug]Evaluating condition for step: 'PostBuildCleanup'
##[debug]Evaluating: AlwaysNode()
##[debug]Evaluating AlwaysNode:
##[debug]=> True
##[debug]Result: True
Starting: PostBuildCleanup
==============================================================================
Task         : Post Build Cleanup
Description  : Cleans the build directories on the agent after the build has finished.
Version      : 3.1.1
Author       : Microsoft Premier Services
Help         : [More information](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/PostBuildCleanup/en-US/overview.md)
==============================================================================
##[debug]Using node path: C:\vsts-agent-1\externals\node\bin\node.exe
##[debug]agent.TempDirectory=D:\agent-1\_work\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_DISABLECERTCHECK
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading VSTS_TASKVARIABLE_CLEANUP
##[debug]loaded 6
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : D:\agent-1\_work\_tasks\PostBuildCleanup_175c8a10-0ef0-11e7-936d-2100de00518d\3.1.1\task.json
##[debug]adding resource file: D:\agent-1\_work\_tasks\PostBuildCleanup_175c8a10-0ef0-11e7-936d-2100de00518d\3.1.1\task.json
##[debug]system.culture=en-US
##[debug]Agent.Version=2.190.0
##[debug]task variable: cleanup=true
##[debug]disableCertCheck=false
##[debug]SystemVssConnection exists true
##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/Ascendon/
##[debug]PBC.LogRawData=undefined
##[debug]System.TeamProject=Core
##[debug]System.DefinitionId=626
##[debug]Build.DefinitionVersion=9
##[debug]Build.BuildId=410828
##[debug]System.JobId=df25c5ee-3d08-5f2f-775d-7ccc0a5e9525
##[debug]System.PhaseDisplayName=Compilation
##[debug]System.JobDisplayName=Compilation
##[debug]PSGer.Build.PollInterval=undefined
##[debug]PSGer.Build.MaxWaitTime=undefined
##[debug]getCurrentRepositoryCleanOption
##[debug]prepareClients
##[debug]Build.Repository.Clean=True
Cleaning up sources...
##[debug]cleanupSources
##[debug]Build.Repository.Provider=TfsGit
##[debug]cleanupGitRepo
##[debug]which 'git'
##[debug]found: 'C:\vsts-agent-1\externals\git\cmd\git.exe'
##[debug]Build.SourcesDirectory=D:\agent-1\_work\2\s
##[debug]Build.Repository.Git.SubmoduleCheckout=False
##[debug]which 'C:\vsts-agent-1\externals\git\cmd\git.exe'
##[debug]found: 'C:\vsts-agent-1\externals\git\cmd\git.exe'
##[debug]C:\vsts-agent-1\externals\git\cmd\git.exe arg: ["clean","-fdx"]
##[debug]exec tool: C:\vsts-agent-1\externals\git\cmd\git.exe
##[debug]arguments:
##[debug]   clean
##[debug]   -fdx
C:\vsts-agent-1\externals\git\cmd\git.exe clean -fdx
fatal: not a git repository (or any of the parent directories): .git

##[debug]Exit code 128 received from tool 'C:\vsts-agent-1\externals\git\cmd\git.exe'
##[debug]STDIO streams have closed for tool 'C:\vsts-agent-1\externals\git\cmd\git.exe'
##[debug]deleteAllContent
##[debug]cleanupGitFolder
##[debug]deleteAllContent
##[debug]cleanupGitFolder
##[debug]deleteAllContent
##[debug]cleanupGitFolder
##[debug]deleteAllContent
Finishing: PostBuildCleanup

**Comment by ReneSchumacher** [comment]
Hi @richardgavel,

we still haven't updated the Post Build Cleanup task to properly work with YAML pipelines. This would require a larger redesign of the task. I'll see if I can get someone to work on this.

**Comment by DhollanderJonas** [comment]
This feature would be really helpful
