### ISSUE TITLE
Pull request statuses + retry for API calls = Too long execution time

### ISSUE THREAD

**Issue by RafalCichon** [MicrosoftPremier/VstsExtensions#154]
Hi there.

I'm using Code Coverage Policy and Warnings Policy.
Because of some security policies I'm not allowed to set the proper permission that is needed to publish policy's result as a pull request status. Before adding retry for API calls there were only one attempt to publish the results (failure reported as warning in the log) and the execution time of the task was about 4 seconds. After adding retry in 8.1.2 the execution time raised to over 1 minute.

How can I turn off publishing the results?

Regards,
Rafał

**Comment by ReneSchumacher** [comment]
Hi @RafalCichon,

thanks for pointing this out. I hadn't thought about the case where permissions where missing when I added the retry mechanism. I'm reducing the number of retries to one with a delay of only two seconds. With this, we'll hopefully catch intermittent connectivity issues and keep the impact to performance as small as possible.

The new version should be online in a couple minutes.

**Comment by RafalCichon** [comment]
Hi @ReneSchumacher.

Thanks for the fix.
I tested it (version 8.1.3) and the task takes few seconds with only one retry.

Thank you and regards.
