### ISSUE TITLE
Create Work Item: Allow to create work Items to be created in different organzations

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftPremier/VstsExtensions#157]
It would be nice to allow to create items in different orgs. It could be possible like the following:

* leverage an existing service connection type
  * for this you would need a connection to each org
* but better would be to just allow setting fields for account and PAT (PAT you already have)
   * this would allow #156 to be more flexible and easy to switch between orgs.

**Comment by ReneSchumacher** [comment]
Hi @SebastianSchuetze,

we have finally implemented this in v2.2.0 of the task, which going through the release process right now. We still haven't decided about the bulk creation of items. This would require a couple changes to the task design.
