### ISSUE TITLE
Post Build cleanup task needs to be upgraded.

### ISSUE THREAD

**Issue by garthbf** [MicrosoftPremier/VstsExtensions#162]
it is throwing a warning message.
==============================================================================
Task         : Post Build Cleanup
Description  : Cleans the build directories on the agent after the build has finished.
Version      : 3.1.1
Author       : Microsoft Premier Services
Help         : [More information](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/PostBuildCleanup/en-US/overview.md)
==============================================================================
##[warning**]This task uses Node 6 execution handler, which will be deprecated soon**. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
Finishing: Clean Agent Directories

**Comment by ReneSchumacher** [comment]
Hi @garthbf,

thanks for bringing this to our attention. We'll update the task as soon as possible so it runs with the Node10 handler. I hope to support YAML builds with the next version as well.

René

**Comment by toddwalstad-eaton** [comment]
Any update on YAML build support?  Any hope for this in 2022?

**Comment by ReneSchumacher** [comment]
Hi @toddwalstad-eaton,

thank you for nudging 😉 I started work on this last week. Not sure how quickly I'll get it done as I'm currently pretty busy with other work, but I do hope that by the end of the month we should have a new version ready.

**Comment by para0056** [comment]
Any update on the YAML support?

**Comment by ReneSchumacher** [comment]
Finally closing this issue. We have updated our docs and provided workarounds for achieving the same cleanup without our task. The task has only limited support for YAML and we will not improve the compatibility, as we cannot be 100% compatible. Thus, we released guidance in our docs. Update to Node 10, 16, and 20 has been done.
