### ISSUE TITLE
Create Work Item:  Allow Team Project to be specified with a variable/plain text in Classic mode

### ISSUE THREAD

**Issue by MichaelReitsma** [MicrosoftPremier/VstsExtensions#163]
We use this extension in Classic mode.
Currently all the fields which have some kind of dialog box such as
-- Work Item Type, 
-- Area Path, 
-- Iteration Path and 
-- Additional Fields
allow the use of plain text or a variable to be used because of the way the picklist is handled.
However the field Team project can only be specified using the drop-down dialog box.
We have a bunch of pipelines where we use this extension and would like to be able to specify all the fields of these tasks with the same set of variables.
We store these in one pipeline Variable Group Library, so changing it here would mean it changes automatically for all pipelines that use this Library and this task. 
That is great except for the fact that we can not specify the Team Project field this way. 
It only accepts a choice from the drop-down list. 

Please change this so that it behaves like the other fields mentioned which allow us to specify plain text or a variable.

**Comment by ReneSchumacher** [comment]
Hi @MichaelReitsma,

thanks for the feedback. Limiting the project field to the values from the drop-down list was a convenience feature (for us and the user) to ensure that only existing projects are used. Since you are free to use any value in YAML, though, it doesn't make sense any more to limit the classic UI in that way. I'll allow additional values in the next version.

René

**Comment by MichaelReitsma** [comment]
Cool, thnx. Any idea as to when this will happen ?

**Comment by ReneSchumacher** [comment]
I'm just looking through our backlog for the CWI task to see what else I might be able to do. Hopefully, I'll have a new version by the end of this week. Currently, I'm the only one working on the tasks :-/

**Comment by MichaelReitsma** [comment]
Ah cool !

**Comment by MichaelReitsma** [comment]
Did you get to finish it just before the weekend ?

**Comment by ReneSchumacher** [comment]
I'm afraid not :-( Too many internal meetings.
I'll make the necessary changes over the weekend and try to get a colleague on Monday morning to review and approve. Sorry for the delay!

**Comment by MichaelReitsma** [comment]
It's ok. We have these meeting-interruptus here to.

**Comment by ReneSchumacher** [comment]
Hi @MichaelReitsma,

sorry again for the delay, but the new version is finally on its way to the marketplace. You should see the new version online in about 10-15 minutes. I'm going to leave this issue open and wait for your final feedback.

**Comment by MichaelReitsma** [comment]
Yup, it works . Thanx a lot from over here..

**Comment by ReneSchumacher** [comment]
Thx for the feedback! I'm closing the issue now. If you miss anything else, just let me know.
