### ISSUE TITLE
Build quality check task fails to pull covered lines down and recognize 0% as lines covered

### ISSUE THREAD

**Issue by Shivanky-ms** [MicrosoftPremier/VstsExtensions#164]
Facing issue in code coverage reported by the Build Quality Check task in our build. We are using BuildQualityChecks@8 version and line coverage. It seems the check fails to retrieve the stored code coverage as it only recognizes 0% of the covered lines. The .coverage files are not empty though.

**Comment by ReneSchumacher** [comment]
Hi @Shivanky-ms,

could you please send the task log from your pipeline to PSGerExtSupport@microsoft.com so we can investigate? If this is a persisting issue, please run your pipeline again with the variables `System.Debug` and `BQC.LogRawData` set to `true` and send the logs from that run.

Thanks,
René

**Comment by Shivanky-ms** [comment]
Hi @René ***@***.***>

This issue is being tracked under mail with subject "Build quality check task fails to pull covered lines down and always recognize 0% as lines covered"(Attached mail).
We shared debug logs over this mail, and we are facing this issue again intermittently. We can merge these two mail threads.

Regards,
Shivanky

**Comment by ReneSchumacher** [comment]
Thanks for the update. I'm closing this issue then because we have the internal thread.
