### ISSUE TITLE
Create WorkItem: Restrict creating link to parent to Team Project or Area Path from Task

### ISSUE THREAD

**Issue by MichaelReitsma** [MicrosoftPremier/VstsExtensions#166]
We are using the Create WorkItem task in classic mode.

The users have to specify a parent id in a pipeline variable that will be used at deploy time to specify the parent of the Task that is going to be created.(Linking section, Link Type: parent, Target: ID)
The system user that is actually creating the Task , Project Collection Build Service, has access rights to all projects we have so creating the parent link succeeds and this is logged in the Task log in the pipeline.
However when the user specifies an id that exists as an object in Azure but in a different project the created parent link can not be removed later on from the WorkItem.
The user can not even remove the Task since that also means removing the link first.
The sort-of superuser, Project Collection Build Service, creates the task and links it to the wrong parent by mistake of the user.
The user needs to contact our administrator who has access to all projects and have him remove the link.
That is cumbersome.

What i propose is the implementation of a checkbox, if possible, so that the creation process of the link first checks if the Area Path or Project Path of the Task is the same as the path(s) of the parent it should link to.
If not then it should not create a link, and tell so in the Task log. The Task should not abort.
The Area Path includes the team the Task is created in, and the link might be to an Azure Epic or Feature . The Azure Feature usually has the same Area Path but the Epic usually has not. That usually has the same path as the Project.
So restricting the to-be-created-WorkItem to the same Project (Team Project field ) seems the safest choice here.
The checkbox could be labeled something like  "Only create link when parent has the same Project" or similar.

Hope to hear from ya

**Comment by ReneSchumacher** [comment]
Hi @MichaelReitsma,

I'll add the request to our backlog. My current idea would be to have a checkbox "Allow linking to work items in other projects", which is checked by default in order to not change the current default behavior.

**Comment by MichaelReitsma** [comment]
Hi, fine by me. I'll uncheck it in our case as soon as it arrives :-)

**Comment by MichaelReitsma** [comment]
Hi,
Any eta on this ?
rgrds

**Comment by ReneSchumacher** [comment]
Working on it.

**Comment by ReneSchumacher** [comment]
I just finished implementation and test for this. The change is now in our PR process and should be published within the next minutes/hour.

**Comment by MichaelReitsma** [comment]
Oh wow, super. Many thnx and enjoy your holidays !

**Comment by ReneSchumacher** [comment]
The new version has been release on Friday last week, so I'm closing this issue now. If you believe something isn't working as expected, please feel free to add additional comments or open a new issue.
