### ISSUE TITLE
not work if pipeline doesnt have error

### ISSUE THREAD

**Issue by kostukp96** [MicrosoftPremier/VstsExtensions#169]
Why its work only if pipeline have error ? I need create item without any error, but this task work only if pipeline have any error

**Comment by ReneSchumacher** [comment]
Hi @kostukp96,

could you explain in a bit more detail which task you are using, how you have configured it and what is not working to your expectations?

**Comment by kostukp96** [comment]
I use "Create work Item" this task only works for me if the previous task failed, if all my tasks completed without errors, the item is not created and I get this error Evaluating: failed() Result: False
![Capture2](https://user-images.githubusercontent.com/74452610/150228606-8c83e99f-e393-4fae-98d4-7cc4838ff78f.PNG)
![Capture1](https://user-images.githubusercontent.com/74452610/150228618-43129633-7e52-4ac5-928b-6eaf764dbab5.PNG)

**Comment by kostukp96** [comment]
This is my conf.
![Capture3](https://user-images.githubusercontent.com/74452610/150229321-a306ba66-d271-466e-9383-d8b2a436a9ad.PNG)

**Comment by ReneSchumacher** [comment]
Hi @kostukp96,

if you see the message "Evaluating: failed()" it means that in the *Control Options* section you have set a condition to run the task only if a previous task has failed:

![image](https://user-images.githubusercontent.com/11600642/150297991-b58da709-9bb3-48ff-a28f-876a05c59cb9.png)

You need to update that condition, so the task runs whenever you want it to run. If you need help, please let me know.

**Comment by kostukp96** [comment]
Thank you, for your help! Its work for me.

**Comment by ReneSchumacher** [comment]
Great, glad I could help. I'm closing the issue then. If you have any other question, please feel free to open a new one.
