### ISSUE TITLE
Failed to load additional fields

### ISSUE THREAD

**Issue by haovanvo** [MicrosoftPremier/VstsExtensions#17]
The extension can not load additional fields when clicking on browse button. The issue is below:

![image](https://user-images.githubusercontent.com/7547579/46182942-b3dbbb00-c2f8-11e8-9063-00a0c7ad4d86.png)

I tried with chrome and Edge browsers. the issue is the same.

**Comment by ReneSchumacher** [comment]
Hi Hao,

thanks for rasing this issue. Can you give me a bit more context about your scenario? Are you using the task on Azure DevOps Services or on TFS? If the latter, which version of TFS are you running? What work item type are you tring to create and are there any special customizations in the work item type? Is the task part of a build or a release definition?

Thanks!
René

**Comment by ReneSchumacher** [comment]
Hi again,

there seems to have been an update to Azure DevOps Services that causes the issue. There now are work item fields that have no field definition in the organization (e.g., System.IterationLevel1 to System.IterationLevel7). I don't know where these fields come from, but I'll add a quick fix to just ignore them for now and work with our product team to get more information about those additional fields.

If all goes well, a fixed version of the task will be available in a couple hours.

René

**Comment by ReneSchumacher** [comment]
Just a quick update: the fix is already in our pipeline, waiting for a colleague to approve my PR.

**Comment by ReneSchumacher** [comment]
Hi Hao,

I just pushed a fixed version (1.0.7) of the task to the marketplace. I'm closing the issue for now. If you still have problems with the task or need additional help, please feel free to contact us again or create a new issue.

Thanks and happy building!
René
