### ISSUE TITLE
CodeCoveragePolicy.Percentage.Covered variable not accessible

### ISSUE THREAD

**Issue by shubham-pathak-03** [MicrosoftPremier/VstsExtensions#174]
**Describe the context**
- **Extension:** BuildQualityChecks
- **Environment:** Azure DevOps Services (cloud) 
  - **Server version:** NA
- **Agent type:** self-hosted agent (Geneva)
  - **Agent version:** https://msazure.visualstudio.com/One/_settings/agentqueues?queueId=29238&view=jobs
  - **Pipeline type:**  yaml pipeline

**Describe the problem and expected behavior**
Trying to output the variable CodeCoveragePolicy.Percentage.Covered via pipeline script as mentioned in https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/CodeCoveragePolicy.md#policy-result-variables. However, this does not yield any value in pipeline script.

**Tell us what you wanted to achieve and what unexpected behavior actually happened.**
Trying to run the build task with following configuration:

![image](https://user-images.githubusercontent.com/87148966/153973127-e76d9575-ec21-41bc-9419-4e3f7f794ab9.png)

No error message was reflected, variable value is not present, however, we can output values pertaining to other baseline build variables as seen in this build [run](https://dev.azure.com/msazure/One/_build/results?buildId=51938650&view=logs&j=b6eff8c6-d969-53dc-259c-9495dad02abd&t=fa71e080-a247-5d64-dd47-949b817322c8&l=77) :

![image](https://user-images.githubusercontent.com/87148966/153972407-c74f2ba1-b9ce-4d93-8e6b-f5ce170d86e0.png)

Output reflects correct baseline build coverage percentage but fails to locate it for current build run:

![image](https://user-images.githubusercontent.com/87148966/153972465-a00999ca-57a7-45ab-ab5a-1a3073f7b6f1.png)

**Add any concrete error messages you see in your pipeline.**
None

**Task logs**
Run your pipeline with the following variables:
- For *BuildQualityChecks*: `System.Debug` and `BQC.LogRawData` set to `true`
- For *CreateWorkItem*: `System.Debug` set to `true`
- For *PostBuildCleanup*: `System.Debug` and `PBC.LogRawData` set to `true`

Send the task log to PSGerExtSupport@microsoft.com and reference your GitHub issue.

**Attention:** The log file may contain sensitive data (e.g., server or organization names, project names, variable information). Please do not attach the log to your GitHub issue and or remove the information from the log file before attaching or sending.

**Comment by ReneSchumacher** [comment]
Closing this issue as discussed internally and fixed.
