### ISSUE TITLE
Best scenario for creating multiple work items

### ISSUE THREAD

**Issue by kostukp96** [MicrosoftPremier/VstsExtensions#180]
Hello! I use script for for generate reports from sonarcloud and whitesource bolt in Azure Devops. After that i am parsing report.json and based on variables, be it bugs or spikes, I create work items with the information I need. The gist of my question is, my script can find many thousands of errors in a file, and correspondingly for each error I will have to create many thousands of work items manually in the azure pipeline, is there any parameter in the "create work item" task that would make it react to my script and automatically created a work item ? That is, so that I don’t have to create thousands of work items in the pipeline, just in case the script detects something or not...

**Comment by ReneSchumacher** [comment]
Hi @kostukp96,

your question/request seems to be similar to #156. You are looking for some kind of batch creation of work items. Currently, the task does not support this, and we haven't really had the time to look into the proposal in the other issue.

For YAML pipelines, you may be able to create a workaround based on a job with a dynamic matrix strategy using variables from a previous job. I haven't tried it and it is certainly not the best solution as it will result in as many pipeline jobs as you need to create work items, but it might be a temporary solution until we have created something for batch work item creation.

**Comment by ReneSchumacher** [comment]
Closing this issue now. Creating batches of work items would require additional logic and increase the task's complexity. Using multiple Create Work Item tasks is the current way to go. We will look into some kind of "expert mode" as described in #156.
