### ISSUE TITLE
BuildQualityChecks missing test coverage by some executed tests

### ISSUE THREAD

**Issue by jiri-skrobanek** [MicrosoftPremier/VstsExtensions#188]
**Describe the context**
- **Extension:** *BuildQualityChecks*
- **Environment:** *Azure DevOps Services (cloud)*
- **Agent type:** *self-hosted agent*
  - **Agent version:** *2.204.0*
- **Pipeline type:** *yaml pipeline*

**Describe the problem and expected behavior**

We run code coverage check and most of the time the check succeeds with

`[SUCCESS] Code coverage policy passed with 88.6317% (67314/75948 blocks).`

However sometimes one of the test assemblies that were executed is seemingly not counted in the coverage percentage. 
And we get his error:

`[ERROR] The code coverage value (15.66%, 9912 blocks) is lower than the minimum value (81%)!`

This is happening for one of 2 BuildQualityChecks that we run in the pipeline.

**Comment by ReneSchumacher** [comment]
@jiri-skrobanek I'm going to reply on the internal email thread and close this issue here.
