### ISSUE TITLE
Update docs to remove over escaping from example yaml warningTaskFilters

### ISSUE THREAD

**Issue by ncook-hxgn** [MicrosoftPremier/VstsExtensions#202]
**Describe the context**
- **Extension:** *BuildQualityChecks*
- **Environment:** *using Azure DevOps Services (cloud)*
- **Agent type:** *self-hosted agent*
  - **Agent version:** *2.213.2*
- **Pipeline type:** *yaml pipeline*

**Describe the problem and expected behavior**
I copied the example value for warningTaskFilters from the yaml sample here
https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md#adding-the-task-to-a-yaml-build-definition

I reduced it down to a single displayName, but the [regex failed](https://github.com/MicrosoftPremier/VstsExtensions/issues/177).

Turns out I duplicated over-escaping from the example. After removing a `\` from `\\s`, it worked.

Please update docs?

**Comment by ReneSchumacher** [comment]
Hey, thanks for pointing that out. I'll fix the docs right away.
