### ISSUE TITLE
Allow formatting of fieldMappings

### ISSUE THREAD

**Issue by KazMiddelhoek** [MicrosoftPremier/VstsExtensions#203]
**Describe the context**
- **Extension:** *CreateWorkItem*
- **Environment:** *Azure DevOps Services (cloud)*
  - **Server version:** *if you are running on-prem, specify the version of your Azure DevOps or Team Foundation Server*
- **Agent type:** *Microsoft-hosted*
  - **Agent version:** *if you are running a self-hosted agent, specify its version*
- **Pipeline type:** *yaml pipeline?*

**Describe the problem and expected behavior**
Allow for formatting of the description. To set a description of the task, we use:
fieldMappings: >
  Description=...
It would be great if we could use formatting for the description, i.e., new-lines, identation etc. Adding new-lines to the fieldmapping makes the rest of the description unvisible (I assume it tries to parse the next field mapping).

**Attention:** The log file may contain sensitive data (e.g., server or organization names, project names, variable information). Please do not attach the log to your GitHub issue and or remove the information from the log file before attaching or sending.

**Comment by ReneSchumacher** [comment]
Hi @KazMiddelhoek and happy new year!

Multiline fields in work items are HTML fields Thus, you can use formatting by using the correct HTML tags in your description. As an example, the following line creates a heading and an ordered list:

```yaml
  fieldMappings: |
    Description=<h2>Important:</h2><ol><li>Use HTML syntax</li><li>Put everything in one line</li></ol>
```

Tbh, we only implemented a simple parsing mechanism for the field mappings. Allowing line breaks directly in YAML would require a more complicated parsing, especially if the field content contains something that could be seen as a field mapping. Unless there is a strong reason for not using a single line of HTML, I'd rather not spend too much time for reworking the field mapping parsing, as it would also require an updated task editor with multiline support.

**Comment by ReneSchumacher** [comment]
I'm closing this issue now since we didn't receive any additional feedback. Using HTML should support all formatting options.
