### ISSUE TITLE
Is it possible to customize the title when there are multiple build quality checks 

### ISSUE THREAD

**Issue by qinl-li** [MicrosoftPremier/VstsExtensions#204]
Hi, 

I added two build quality checks in the pipeline. One is to check code coverage using a fixed threshold. 
The other one diff from the baseline. 

<img width="450" alt="image" src="https://user-images.githubusercontent.com/63257243/214734202-d7ed7e67-15b8-4eed-be94-27058e10c00a.png">

As you can see, they appear the same on the page. Is it possible to customize them?

**Comment by ReneSchumacher** [comment]
Hi @qinl-li,

you can use the `runTitle` property to separate the two build quality checks. See [reporting options](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md#reporting-options) for more information.

**Comment by qinl-li** [comment]
@ReneSchumacher Thanks for your quick reply! I have played around with that property and it doesn't seem to work: 
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/63257243/214958691-78c412f8-cfe1-4937-b490-869cf6e3695c.png">

Here is the task definition: 
<img width="884" alt="image" src="https://user-images.githubusercontent.com/63257243/214958885-c3fd1f66-6049-41ca-a7e3-99446b38415e.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/63257243/214959079-a711fe34-0186-4455-96f6-bbff305e7e5e.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/63257243/214959123-6c7f9ad7-ec12-4236-b9f5-d60a9f749b82.png">

**Comment by ReneSchumacher** [comment]
Hi again,

I just realized that you're using the pull request feature. Unfortunately, we currently don't put the run title into the PR status message. We could easily add the run title to the PR status, but I'm afraid that this might lead to very long status messages which are then cut off by the UI. Let me look into this. Maybe we can just use the first couple characters (maybe 10-20) from the run title and update the status like this: "{Run Title}: {Status Message}" (e.g., "Fixed Threshold: Code coverage policy passed with 89.9358% (420/467 branches)."

**Comment by qinl-li** [comment]
Sounds good! That would be very helpful! thank you!

**Comment by ReneSchumacher** [comment]
Hi @qinl-li,

I'm closing this issue now since I (finally) have implemented your change in the next version (v9.0.0). I'll hopefully release the update by the end of this week. If you need additional assistance or the new solution doesn't meet your needs, please feel free to either comment on the closed issue or open a new one.

Thanks for your feedback!
