### ISSUE TITLE
Proxy Auth

### ISSUE THREAD

**Issue by Danlewis3** [MicrosoftPremier/VstsExtensions#21]
If you are behind a proxy this extension wont allow you to connect to create the workitem

**Comment by ReneSchumacher** [comment]
Hi Dan,

thanks for reporting this issue. The task should automatically pick up the proxy settings from the agent itself. However, we haven't explicitly tested that as we don't have a proxy environment yet.

How did you configure your task? Did you follow the steps outlined at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=vsts&tabs=windows?

René

**Comment by ReneSchumacher** [comment]
Hi Dan,

could you resolve the issue or do you need additional assistance?

René

**Comment by ReneSchumacher** [comment]
Hey Dan,

I'm closing this issue for now as I didn't receive any feedback from you. If the problem still persists and you need additional help, please let us know.

Happy building!
René
