### ISSUE TITLE
Create Work Item: Specify values for duplicate key fields like State<>'Done'

### ISSUE THREAD

**Issue by MichelJansson** [MicrosoftPremier/VstsExtensions#211]
Thanks for creating this extension. We are looking to use it to create bugs if scanner finds any issues. Everything works nicely to create the work item, except that I cannot figure out how to setup the duplicate check to satisfy our needs.

Is there any way to override or customize the generated WIQL?
Basically what we want to do is something like the below where we can have control over the supplied values to the fields.
``` yaml
keyFields: |
  System.Title
  System.State<>'Done'
```

Scenario:

1. Pipeline is running on schedule
2. Work item is created for the issue with a somewhat static title.
3. PO or Team might change work item state to approved etc. and edit some other fields during backlog refinement.
4. Some time passes and the pipeline is run again
5. This time we already have an refined item and don't want another.
    1. But since the item is not in state New any more a key field of just System.State won't do, and a new item would be created
    2. So we leave the State out of the key fields so it's being detected as a duplicate.
6. Team resolves work item and it's state gets set to done.
7. Some more time passes and the pipeline is run yet again.
8. Now we want a new work item as we no longer have a work item that could be worked on since it's set to done and is hidden.
    1. But since we do not have state among the keyFields the old, completed item is found and treated as duplicate and the new requirement is lost.

**Comment by MichelJansson** [comment]
@ReneSchumacher, Thanks for the update.

I did figure out a workaround for my immediate specific issue by using the `Closed Date` as key field which is null until state is set to any of the closed states.

But I still think this would be a great thing to support, as that would be more intuitive and be more generic.

Is this extension pure closed source, or is there anywhere we could do a PR?

**Comment by raydixon** [comment]
@ReneSchumacher it sounds like you just wrote a pretty strong justification for making this open source. 🙂

**Comment by ReneSchumacher** [comment]
Hi all,

the complex update rules are now implemented in v2.x of the task. Closing this issue now. Please let me know if something is missing or not working as you expect it.
