### ISSUE TITLE
CreateWorkItem - A potentially dangerous Request.Path value was detected from the client

### ISSUE THREAD

**Issue by jakaxd** [MicrosoftPremier/VstsExtensions#228]
**Describe the context**
After adding the CreateWorkItem task into my yaml pipeline, I am experiencing the following error:

##[error]﻿{"$id":"1","innerException":null,"message":"A potentially dangerous Request.Path value was detected from the client (*).","typeName":"System.Web.HttpException, System.Web","typeKey":"HttpException","errorCode":0,"eventId":0}

However, if I create a seperate pipeline - the task works fine and is able to create a work item.

Expecting that the task will successfully create a work item and looking for some advice on what could be causing the issue.

- **Extension:** CreateWorkItem
- **Environment:** Azure DevOps Services (cloud)
- **Agent type:** Self-Hosted 
  - **Agent version:** 3.23.2
- **Pipeline type:** yaml

Here is the task definition:

```
  - task: CreateWorkItem@2
    condition: | # Only create a work item if there are changes in the plan and the build is scheduled
      and(
        succeeded(),
        eq(variables['Build.Reason'], 'Schedule'),
        eq(variables['plan.changesPresent'], 'true')
      )
    displayName: 'Create Work Item'
    inputs:
      teamProject: 'REDACTED'
      workItemType: Task
      title: '$(Build.Repository.Name) - ${{upper(parameters.Environment)}} - Drift Detected'
      areaPath: 'REDACTED'
      iterationPath: 'REDACTED@currentIteration'
      fieldMappings: |
        Description=Scheduled Plan has automatically created this task due to Drift Detection in the following run: $(Build.BuildNumber).
        Priority=4
      associate: true
      # ===== Linking Inputs =====
      linkWorkItems: true
      linkType: 'System.LinkTypes.Hierarchy-Reverse'
      linkTarget: 'id'
      targetId: ${{ parameters.WorkItemId }}
      # ===== Duplicate Inputs =====
      preventDuplicates: true
      keyFields: |
        System.Title
        System.AreaPath
        System.State==[New, To Do, In Progress, Blocked, Testing]
      updateDuplicates: true
      updateRules: |
        System.History=Scheduled Plan has detected another Drift in run: $(Build.BuildNumber)
```

**Comment by ReneSchumacher** [comment]
Hi @jakaxd,

your task configuration looks good at first glance. However, the error message indicates that based on your input, the task created an API call with parameters that are deemed dangerous. This usually indicates an unescaped character or something similar. Could you please run your pipeline again with the variable `System.Debug` set to `true` and send the task log to PSGerExtSupport@microsoft.com? Please redact sensitive information in the log as needed.

The debug log should tell us which part of the task is trying to make the failing call.

**Comment by jakaxd** [comment]
Hi @ReneSchumacher, 

thank you for the quick response! I have sent over the logs.

**Comment by ReneSchumacher** [comment]
Hey,

we have discussed this internally and have decided against a change of our task. If we simply ignore secrets for specific fields like team project, area path, iteration path, work item type, etc., we might make them visible in the logs or in the work item itself. Thus, it's "safer" to break functionality if - for whatever reason - someone believes that the work item type or project must be a secret value than leaking the secret.

**Comment by jakaxd** [comment]
Thanks @ReneSchumacher, we have managed to workaround the issue. Your help has been great in understanding the solution - if perhaps you do see this issue again, for us specifically, it was a combination of using the organisation url and project name as secrets. Once we removed those, it solved the problem.

I will close the issue out now, once again - thank you for the support!
