### ISSUE TITLE
CreateWorkItem Failed to run task on both Windows and Unbuntu agents

### ISSUE THREAD

**Issue by bay47131** [MicrosoftPremier/VstsExtensions#229]
- Extension:   CreateWorkItem
- Environment:   Azure DevOps/Team Foundation Server (on-prem)
- Server version:   Azure DevOps Server 2020 Update 1.1
- Agent type:   Self-hosted agent
- Agent version:   2.181.2

Tried to run this task on Ubuntu 20.04 and windows agent, both failed.
- Ubuntu:  [error]The current operating system is not capable of running this task. That typically means the task was written for Windows only.
- Windows:  [error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

**Comment by ReneSchumacher** [comment]
Hi @bay47131,

thanks for reporting this. I believe we forgot to update the minimum agent version in our task metadata. I can see that we're still requiring 2.144.0 but we actually need at least [2.206.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.206.1). Our task currently only supports the Node16 execution handler, which was introduced in v2.206.1 of the agents.

Please update your agents to a at least v2.206.1. We will fix the minimum agent requirement with our next release of the task. With this, the pipeline run would have triggered an automated agent update or - if that is not possible - would have failed with an error pointing out the agent version requirement.

Sorry for the inconvenience.

**Comment by bay47131** [comment]
thank you for your quick response.
