### ISSUE TITLE
Do you plan to migrate BuildQualityChecks as a Github Action?

### ISSUE THREAD

**Issue by ranouf** [MicrosoftPremier/VstsExtensions#235]
Hi,

We are currently using this excellent extension BuildQualityChecks on Azure Dev Ops. We are currently migrating our Builds and Deployment to Github.

I looked for BuildQualityChecks in github action without succes yet. Does it exist? Do you plan to develop as a Github action soon? Is there an alternative you recommend to block a build when X% is not reach?

Thanks

**Comment by ReneSchumacher** [comment]
Hi @ranouf,

there is currently no version of BQC for GitHub Actions and we don't have any near-time plans to build a GitHub Actions version. The main reason is that GitHub does not have a central store for build information including test results and code coverage like Azure DevOps has. Thus, our task cannot simply rely on preprocessed data but would have to evaluate coverage data itself. In addition, we would need to handle exchange of historical coverage data between action runs to support breaking builds on previous build values.

We will first move the Azure DevOps task to custom coverage parsing etc. Then we can think about a GitHub Actions version of the task.
