### ISSUE TITLE
Build Quality Check step does not match the code coverage with VS test code coverage for dot net core

### ISSUE THREAD

**Issue by pratikshadange** [MicrosoftPremier/VstsExtensions#24]
Hi,

I have added BuildQualityCheck step in the build definition. Dot net core Test project is added for the core web api. I have used .Net Core build step before BuildQuality Check step. When code coverage is checked using Test Explorer in Visual studio, it shows 80% or more. But the same code on build shows ~30% in Build Quality check step. Shouldn't they show similar values for code coverage? 
I also added Code Coverage Protector/Comparer step to see the difference between code covered in two successive builds , that also shows shows the values like ~30%. 

![image](https://user-images.githubusercontent.com/45597464/49445780-aeb75280-f7f8-11e8-9ea1-d6e7c5390269.png)
![image](https://user-images.githubusercontent.com/45597464/49445802-c1ca2280-f7f8-11e8-8100-a914af33dfe7.png)

**Comment by ReneSchumacher** [comment]
Hi,

did you run the tests with the Visual Studio Test task or the Dotnet task and are you sure that all code coverage data has been properly published before running the Build Quality Checks task?

One thing that stands out in your screenshots is that the coverage file only lists 2556 total blocks while our task reports 18762 total blocks. This is a huge difference and I assume that the task is looking at the aggregated result of multiple code coverage data sets. Could you post a screenshot of the code coverage summary shown in the build result page?

René

**Comment by pratikshadange** [comment]
I ran the dot net core step for Tests. 
![image](https://user-images.githubusercontent.com/45597464/49497449-76625380-f88e-11e8-8535-0c4e11bc7512.png)
It executed all the unit test cases successfully and published using one more dot net core step to publish command. Then Build Quality check step is placed.

The code coverage blocks shown different and thats why the difference is. 
Current Code coverage shown after build using Build quality check screenshot -- 
![image](https://user-images.githubusercontent.com/45597464/49498539-61d38a80-f891-11e8-802b-c7a93cef478e.png)

Its shows more blocks because of Automapper and Moq.dll. It should not check for references, right ?

For same code when I run test cases locally in VS Test explorer and then run code coverage for test cases, it shows- 
![image](https://user-images.githubusercontent.com/45597464/49498503-46687f80-f891-11e8-9150-85d3443e4f28.png)

**Comment by ReneSchumacher** [comment]
I'm not an expert on dotnet core but I believe that the standard test run started by dotnet test does not exclude references from coverage instrumentation. You'll probably have to use runsettings as described at https://docs.microsoft.com/en-US/dotnet/core/tools/dotnet-test?tabs=netcore21 and https://github.com/Microsoft/vstest-docs/blob/master/docs/RunSettingsArguments.md to exclude those assemblies.

**Comment by ReneSchumacher** [comment]
Great to hear that you solved the issue. I'm closing the issue now, but if you need anything else, please feel free to open another issue or send an email to PSGerExtSupport (at) microsoft.com.

Happy building!
René
