### ISSUE TITLE
BuildQualityChecks on (onprem)AzureServer2020.1  is broken in latest release

### ISSUE THREAD

**Issue by peterthim** [MicrosoftPremier/VstsExtensions#240]
**Describe the context**
- **Extension:**  BuildQualityChecks,
- **Environment:**Azure DevOps/Team Foundation Server (on-prem)?*
  - **Server version:** 2020.1 (unable to verify as i don't got hard server access but it was installed in 2022 jan so i doubt its 2022
- **Agent type:** Selfhosted
  - **Agent version:** 2.181.2
- **Pipeline type:** YML

**Describe the problem and expected behavior**
unable to start as task require Agent.Version -gtVersion 2.206.1
latest supplied Agent version for windows on that server is 2.181.2

version 9.1 worked fine 9.2.1do not work 
**Task logs**
##[error]No agent found in pool software-agents satisfies both of the following demands: XXXXXXXX  and agent.os, Agent.Version. All demands:  Agent.Version -gtVersion 2.206.1

**Comment by ReneSchumacher** [comment]
Hi @peterthim,

sorry for the inconvenience created here. We had an issue with v9.x of our task as we upgraded it to a later version of the Azure Pipelines libraries, which were only fully compatible with newer agent versions. Unfortunately, when we released the first version 9.x, we forgot to update the minimum required agent version and fixed that with the latest release. We were a little torn between doing this as part of a patch/minor update and doing a major version upgrade, even though the functionality of the task hadn't really changed (in fact, we just fixed an issue). In the end, we decided to go for a patch/minor version change.

To fix the issue, you must upgrade your agent version to a version greater than or equal 2.206.1. This should happen automatically for customers using Azure DevOps Services and having agents that can access the internet. For on-premises servers, you can either manually install a newer agent from https://github.com/microsoft/azure-pipelines-agent or follow the instructions given [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2022&tabs=yaml%2Cbrowser#agent-version-and-upgrades). My recommendation would be upgrading to an agent version 3.x, as the 2.x agents are still using the outdated .NET Core 3.x and are not receiving any security updates anymore. Please read [this](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops) information to ensure that your agent machines have compatible operating systems installed.

If you cannot upgrade the agent (or put the new agent version onto the server for auto-upgrades) quickly enough, I recommend fixing the task version to 9.1.0 in yaml by giving the full version like this:

```yaml
...
  - task: BuildQualityChecks@9.1.0
    inputs:
      ...
```

**Comment by peterthim** [comment]
Thanks for the fast input  Workaround worked and upgrading to the latest agent actually worked to so we are opting for that.

**Comment by ReneSchumacher** [comment]
Great, thank you for confirming that you are unblocked now. Upgrading the agents is definitely the best option.

I'm closing the issue now, but feel free to open another one or post a new comment in the closed one if you need additional help.
