### ISSUE TITLE
Create work item task hangs

### ISSUE THREAD

**Issue by sanyappc** [MicrosoftPremier/VstsExtensions#30]
`TaskInputs.validateIdentityValue("Abcdefghi Bcdefghijklmn <a.bcdefghijklmn@opqrst-uvwxyz.com>")`'s execution takes 3 hours. Moreover, this value is interpreted as invalid.

**Comment by ReneSchumacher** [comment]
Hi Alexander,

the function merely does a regular expression test on the value. I tweaked the expression a bit and it now finishes in under a second and evaluates your address correctly. I won't be able to push out a new version until the end of the week, though. Please stay tuned for the new version and sorry for the inconvenience!

René

**Comment by ReneSchumacher** [comment]
Hi again,

the fix goes out today. I'll close the issue for now. If you continue to have problems with the task, please feel free to reopen the issue or create a new one.

Happy building!
René
