### ISSUE TITLE
How to reset baseline with `BuildQualityChecks`

### ISSUE THREAD

**Issue by vladbarosan** [MicrosoftPremier/VstsExtensions#32]
Hello, we are trying to reset the baseline test coverage for `BuildQualityChecks` but doesnt seem to work.

What we are doing:
 - We have build definition `A` that checks coverage on PR's and also runs on master to update the baseline.
 - We have build definition `B` which runs on master and we added the force paramter to reset the baseline and we refer to the `A` definition.

Is this the proper way to do it? or should we just have the force and the baselien will update when in runs on mater ( but not on the PRs ) ?

**Comment by vladbarosan** [comment]
@almtcger can you give some pointers here please ?

**Comment by ReneSchumacher** [comment]
Closing this issue as it has already been fixed through the support email channel.

For future reference: you can set the variable BQC.ForceNewBaseline to true to force the policy to pass and create a new baseline build.
