### ISSUE TITLE
Upper Threshold not working

### ISSUE THREAD

**Issue by lsantos10** [MicrosoftPremier/VstsExtensions#33]
I've set the value to 90%, but the quality check still fails because my build dropped the coverage from 95% to 93%. According to documentation any build with coverage above 90% shouldn't be a problem.

**Comment by ReneSchumacher** [comment]
Hi!

I'm sorry for the confusion, I'd call this an "unprecise documentation" issue. The current version of the task does indeed fail the policy as soon as the coverage value decreases, even if it stays above the upper threshold. The threshold is only used to pass the policy if your coverage does not increase even though you forced increasing coverage. I'll add a new option with the next update to ignore decreasing coverage as long as you stay above the upper threshold.

Sorry for the inconvenience,
René

**Comment by ReneSchumacher** [comment]
Hi again,

I again have to apologize for the long delay. We have been waiting for some backend changes in Azure DevOps to fix another issue and these changes have finished rolling out today. We'll release a new version of the task by tomorrow at the latest and this version will have the option I mentioned above. I'll close the issue now as it should be resolved. If you still encounter problems, please let us know!

Sorry for having you waiting for so long and happy building!
René
