### ISSUE TITLE
Prevent Duplicates ignored if the field is number

### ISSUE THREAD

**Issue by TsuyoshiUshio** [MicrosoftPremier/VstsExtensions#36]
This is very small feedback. 

When we specify a filed which is only have a number. It will ignore the preventing duplicate settings.  The reason is, it seems not hit without double quote. 

# Settings example 

```
Title 
$(System.PullRequest.PullRequestId)

Duplicate > Key fields
System.Title
```

You can see the log said it is refer as a number. 

# Result

If you have a several CI with the same PR, it creates work items for one PR. 

# Log

```
Final WIQL query: SELECT System.Id FROM WorkItems WHERE System.TeamProject = 'DevSecOps' AND [System.Title] =  57
##[debug]queryWorkItems
The WIQL query string (SELECT System.Id FROM WorkItems WHERE System.TeamProject = 'DevSecOps' AND [System.Title] =  57) is invalid!
##[debug]TF212023: You cannot compare fields with different data types in the WHERE clause of a work item query. The error is caused by «[System.Title] = 57».
```

**Comment by ReneSchumacher** [comment]
Hi Tsuyoshi,

thanks for reporting this. This is indeed a bug in our WIQL generation that we'll fix in the next version. An update should be available within this week.

Thanks,
René

**Comment by TsuyoshiUshio** [comment]
Thank your! Also thank for the great extension. This extension is very useful.

**Comment by ReneSchumacher** [comment]
Hi again,

the bug has been fixed and the new version is in the release pipeline. You should see an updated version in a couple minutes. Thank you for the good feedback and

happy building!
René
