### ISSUE TITLE
Filtered warnings are not taken into account when comparing total warning count with previous build?

### ISSUE THREAD

**Issue by utna666** [MicrosoftPremier/VstsExtensions#38]
![2019-06-26_12h06_53](https://user-images.githubusercontent.com/5910372/60171657-5636b980-980b-11e9-8f2f-050320cc8e3b.png)

**Comment by ReneSchumacher** [comment]
Hi @utna666,

I assume the log output is a bit confusing and perhaps we should rename it to "warnings after applying the filter". Filtered warnings shows the number of warnings that still remain after applying all warning filters. Thus, in your case the filter apparently matches all existing warnings. If your filter would have reduced the number of warnings, you would see something like

```
Total warnings: 6
Filtered warnings: 0
```

Did you try to apply a special warning filter? Perhaps I can help you fix the filter to achieve your desired outcome.

René

**Comment by utna666** [comment]
Hi @ReneSchumacher,

if I understand correctly, the 'Warning Filters'-Property is not there to **filter out / ignore** insignificant warnings but to let relevant warnings "through"?

**Comment by woehrl01** [comment]
Hi @utna666 ,

that's correct. The 'Warning Filter'-Property selects only the warnings you are interested in.

> **Docs:** Specify a list of regular expressions (one per line) that only match the types of warnings you are looking for and the policy will evaluate only those warnings.

Lukas
