### ISSUE TITLE
Wrong link in task

### ISSUE THREAD

**Issue by vtbassmatt** [MicrosoftPremier/VstsExtensions#44]
Hi :wave: I'm a PM on Azure Pipelines. A customer reported a bug to us, but we think it's in your task. See this link for more:  https://developercommunity.visualstudio.com/content/problem/694040/more-information-link-on-post-build-cleanup-pipeli.html

**Comment by woehrl01** [comment]
Hi Matt,

thank you! We'll have a look!

Best
Lukas

**Comment by woehrl01** [comment]
We updated the link accordingly and published a new version. Thank you for forwarding that issue @vtbassmatt .
