### ISSUE TITLE
Create Work Item task, updateRules with Iteration Path @currentIteration

### ISSUE THREAD

**Issue by jwikman** [MicrosoftPremier/VstsExtensions#46]
I'm using the "Create Work Item" task for creating work items in my multistage yaml pipeline.

I'm using the preventDuplicates and updateDuplicates to update existing Work Item instead creating new ones. 
If I have a duplicate I want to update the Iteration Path to the current Iteration.

I'm using this for new Work Items, which works great:
```
    iterationPath: '$(WorkItemTeamID)@currentIteration'
```    
But having @currentIteration in the updateRules fails
```
    updateRules: |
      State=New
      Iteration Path=$(WorkItemTeamID)@currentIteration
```

`$(WorkItemTeamID)` is a pipeline variabel set before this is run

The only clue I get about this is the debug message:
`
##[debug]TF401347: Invalid tree name given for work item 26413, field 'System.IterationPath'.
`

**Comment by ReneSchumacher** [comment]
Hi Johannes,

thanks for reporting this issue. We can reproduce it and already identified the bug in the code. For work item updates we simply forgot to resolve the correct iteration path from the special value {team ID}@currentIteration. Sorry for that. We'll fix the issue tomorrow and publish an updated version of the task. The update should be available tomorrow.

Thanks,
René

**Comment by jwikman** [comment]
Thanks René,

That was fast! 👍

**Comment by ReneSchumacher** [comment]
Hi again,

we just published version 1.5.4 of the task that contains the fix, thus, I'm closing the issue. If the update still doesn't work for you or you run into other issues, please feel free to comment again, create a new issue or send us an email to PSGerExtSupport@microsoft.com.

Happy building!
René

**Comment by jwikman** [comment]
@ReneSchumacher where can I see what version I have installed in our DevOps?

**Comment by ReneSchumacher** [comment]
Unfortunately, you can only see it in the task log. If you're running on Azure DevOps Services it will automatically update to the latest minor and patch version. For Azure DevOps Server you can look into the local marketplace (http://your-tfs/_gallery/manage). You'll see the version there and can update the extension to the latest version.

**Comment by jwikman** [comment]
Aah, there it was! (I'm on DevOps Services)

It's version 1.5.4, so I'll just give it a spin then.

**Comment by jwikman** [comment]
@ReneSchumacher  I can confirm that this now works as expected.

Thanks a lot for fast action!
