### ISSUE TITLE
Post Job Cleanup

### ISSUE THREAD

**Issue by joemorin73** [MicrosoftPremier/VstsExtensions#49]
It appears that the postjob cleanup will not execute if the build is in a git pipeline that performs a postjob checkout cleanup.  Any work around for this?

**Comment by ReneSchumacher** [comment]
Hi Joseph,

the task should work for git repos. Could you run your build again with the variables System.Debug and PBC.LogRawData set to true and send the logs (both the task log as well as the post job script log) to PSGerExtSupport@microsoft.com? I'll take a look as soon as possible.

Thanks,
René

**Comment by ReneSchumacher** [comment]
Hi again,

I'm closing this issue now as we haven't received any new information. If the issue still exists, please feel free to post an update and we'll open the issue again.

René
