### ISSUE TITLE
BuildQualityChecks Hangs Sometimes for .Net Solution w/o Tests

### ISSUE THREAD

**Issue by vfeier** [MicrosoftPremier/VstsExtensions#5]
BuildQualityChecks will hang sometimes, while running on a **.Net solution which contains no tests**.
This is the log of a hanging build:

> Starting: Check build quality
> 
> Task         : Build Quality Checks
> Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
> Version      : 4.0.3
> Author       : Microsoft Premier Services
> Help         : [[Docs]](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
> 
> SystemVssConnection exists true
> Validating build warnings policy...
> Counting warnings from tasks:
> ....
> Total warnings: 9
> Filtered warnings: 9
> Validating code coverage policy...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Unable to get code coverage data within the maximum wait time.
> Total blocks: 0
> Covered blocks: 0
> Code Coverage (%): 0
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> Waiting for code coverage data...
> .....
> .....
> [Keep getting "Waiting for code coverage data..."]

The build was running for ~37 minutes, out of which around 34 were spent hanging at build quality checks.
On a build that doesn't fail, the task ends immediately after:

> Unable to get code coverage data within the maximum wait time.
> Total blocks: 0
> Covered blocks: 0
> Code Coverage (%): 0

**Comment by almtcger** [comment]
Hi Vlad,

I found the issue to be caused by a typo in our waiting code and already fixed it. The new version 4.0.4 should not have this issue anymore.

Thanks for reporting this!
René
