### ISSUE TITLE
Warning from HTML (aspx)

### ISSUE THREAD

**Issue by raphaelmoreira** [MicrosoftPremier/VstsExtensions#63]
Hello.
This extension can check HTML warnings too?

In Visual Studio (mine is 2019), when you open a page (ASPX), the IDE start some kind of validation that show some warnings like below:

My App:
![image](https://user-images.githubusercontent.com/5034220/72275780-5b275300-360d-11ea-8467-bc8a9cb69f12.png)

If I just close the ASPX, the warning goes away.

What I try:

I add this:

**warningFilters**: '/(Validation \(XHTML5\): Element|cannot be nested within element)'
**inclusiveFiltering**: true

As you can see, my regex works: [https://regex101.com/r/5cakOX/1](https://regex101.com/r/5cakOX/1)

But the build can't find this warning.
Can I do something about this?

Thank you.

**Comment by ReneSchumacher** [comment]
Hi @raphaelmoreira,

I'm afraid the task won't be able to see those warnings. The Build Quality Checks task operates on the log file created by the build process. Thus, those warnings would have to appear in the regular output of MSBuild when compiling an ASP.NET web application. However, MSBuild simply ignores those warnings. I don't know if there are any standalone markup validators available. If you , you could run them in a separate build step and then use custom warning filters to evaluate their warnings.

I'm closing this issue as we cannot really help here. If you find a validation tool that is able to create those warnings and need help configuring the warning filters, feel free to open another issue.

René
