### ISSUE TITLE
BuildQualityChecks: allow fail on absolute increase of uncovered branches

### ISSUE THREAD

**Issue by mjvk** [MicrosoftPremier/VstsExtensions#68]
Currently the build quality checks only checks on covered branches/lines/blocks. This becomes troublesome. If you remove covered code this means your absolute and relative percentages drop. In practice it means that you start adding coverage in a different place only tangentially related to your pull request. If you instead would use absolute uncovered branches and do not allow this to increase you are:

- not allowed to add new code that adds uncovered branches (i.e. reduce coverage), and
- allowed to remove covered code.

Or am I missing something here? I think this would be very helpful!

**Comment by ReneSchumacher** [comment]
Hi @mjvk,

I actually never thought about that. You're absolutely right, the moment you start removing covered code you have to add additional tests to keep coverage values up. I put your idea on the backlog and try to implement it over the weekend.

Thanks for the suggestion!

René

**Comment by ReneSchumacher** [comment]
Hey @mjvk,

I just finished adding the feature to the code coverage policy. The task is now waiting for code review, which is hopefully done tonight. An updated version should be out either today or tomorrow.

René

**Comment by mjvk** [comment]
@ReneSchumacher  Wow that's quick! Even over the weekend! Thank you very much.

**Comment by ReneSchumacher** [comment]
Thx :) It's after all a spare time project. I'm not getting paid by Microsoft for developing extensions - even though I spend a fair amount of time doing so during my working hours ;-)

**Comment by ReneSchumacher** [comment]
The new version 6.3.0 with support for evaluating uncovered elements is public now. Let me know if this matches your expectations of if you need anything else.

Happy building,
René

**Comment by mjvk** [comment]
Seems to work like a charm, thank you
