### ISSUE TITLE
CoverageVariance documentation

### ISSUE THREAD

**Issue by mjvk** [MicrosoftPremier/VstsExtensions#70]
I think it would be nice to add to the CoverageVariance documentation if it is based on percentage or absolute?

**Comment by ReneSchumacher** [comment]
Hey,

it can be both and depends on how you configure the policy. If you set the coverage delta type to absolute (the default), variance is absolute variance (e.g., number of lines, blocks, etc.). If you change the delta type to percentage, variance is also a percentage value.

Do we need to make that clearer in the docs?

**Comment by mjvk** [comment]
Clear I guess, and easy to find by trial and error.
