### ISSUE TITLE
[BQC] Publish "PR Status" instead of failing the build

### ISSUE THREAD

**Issue by Bouke** [MicrosoftPremier/VstsExtensions#73]
Currently this quality gate can optionally fail the build, but doesn't participate in the "PR Status". So this means that I can either fail the pipeline (which is disruptive to automated testing), or I'd have to ask team members to verify the build warning count (which they wont). So, I would be very happy if this extension could post a ok/fail status check to the accompanying PR instead.

**Comment by ReneSchumacher** [comment]
Thanks for your suggestion! I've put it on our backlog and do hope to have time for this early next week. We're already working on an update of the BQC task that creates result variables for all policies so this would be a nice addition to that release.

**Comment by ReneSchumacher** [comment]
We have added this feature in v6.4.0 of the task which should be available in the marketplace in about an hour. I'm going to close this issue now but please feel free to provide any feedback and let us know if this meets your expectation.

Happy building,
René

**Comment by Bouke** [comment]
Thank you, this seems to be working as expected.

I probably need `continueOnError: true` on that task now, as I only want the PR status and not to fail the build.
