### ISSUE TITLE
If you add a display name to build, warnings will not fail the build

### ISSUE THREAD

**Issue by NorthHighlandNicole** [MicrosoftPremier/VstsExtensions#76]
Hello,

I was using this extension as a task in my .yaml file to ensure that any warnings at all will fail the build. I t was working fine, and suddenly it seems not to do so. I couldn't understand what had changed, and looked at my commits.

Finally I found that when I removed the `displayName` from my build step, it resolved the issue. Sounds like someone referenced the `displayName` instead of `task` in the QC extension. Please fix, I would never have thought I can't give my step a friendly name.

**Comment by ReneSchumacher** [comment]
Hi,

this behavior is expected and documented as well (see https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/WarningsPolicy.md#taskFilters). For historical reasons the task looks at the display name when filtering the timeline as older versions of the build system didn't have the actual task name in the build timeline. Thus, our docs state:

>*The matching is done by looking at the timeline name of each task, i.e., the name displayed in the list on the left hand side of the build summary view. **If you change the display name of a task in your build definition, make sure to update the task filters appropriately.***

To make things easier, though, I believe it's best if we match on both task name and display name. I'll make sure the next version of the task will be updated accordingly.

René

**Comment by ReneSchumacher** [comment]
We've fixed this in v6.4.0 of the task. Filtering is now done based on the display name and the internal task name, which should cover most of the common scenarios.
