### ISSUE TITLE
[BQC] Support for checking logs from specific task in multi-stage multi-job pipeline?

### ISSUE THREAD

**Issue by Bouke** [MicrosoftPremier/VstsExtensions#77]
I was wondering if BQC is able to handle warnings from a pipeline using multi-job / multi-stage, and how I would need to configure that?

I have the following pipeline:
```
stages:
- stage:
  jobs:
  - job: AA
    steps:
    - task: Build
    - task: BQC
  - job: AB
    steps:
    - task: Build and Package
```

What I want is for BQC to *only* apply to the job "AA", and only compare the warning count from previous builds of that same job "AA". Or even: the task Build" inside job "AA". Currently "Build" (AA) produces 3863 warnings and "Build and Package" (AB) produces 2871 warnings.

With the filter set to `warningTaskFilters: 'Build'`, the output of the task is this. Note that the "Build" step isn't listed for 12933:
```
Counting warnings from tasks:
- Build
-   Running MSBuild log analysis...
-   Total warnings: 3863, Filtered warnings: 3862
Total warnings: 3863
Filtered warnings: 3862
Found baseline build with ID 12933.
Counting warnings from tasks:
- Set Version and Build Number
-   Total warnings: 0, Filtered warnings: 0
- Build and Package
-   Running MSBuild log analysis...
-   Total warnings: 2871, Filtered warnings: 2869
Total warnings: 2871
Filtered warnings: 2869
```

With the filter set to `warningTaskFilters: '/^Build$/'`, the output of the task is this. Note that no matching build task could be found:
```
Counting warnings from tasks:
- Build
-   Running MSBuild log analysis...
-   Total warnings: 3863, Filtered warnings: 3862
Total warnings: 3863
Filtered warnings: 3862
Found baseline build with ID 12933.
The specified task filters did not match any build task.
```

The build summary to confirm that there are indeed warnings generated from a build step called "Build":

![image](https://user-images.githubusercontent.com/235882/74280110-64930080-4d1c-11ea-8758-e872c405b09c.png)

**Comment by ReneSchumacher** [comment]
Hey,

we actually added code to handle this with version 6.2.x of the task. BQC task _should_ always compare warnings against the correct corresponding job from the previous build. Could you please run your build again with the variables _System.Debug_ and _BQC.LogRawData_ set to _true_ and send me the logs from the BQC task via email to PSGerExtSupport@microsoft.com? Also, could you send me the YAML file with your pipeline definition? I'll have a look why BQC task lists warnings from a different job.

Thanks,
René

**Comment by Bouke** [comment]
After reviewing those debug logs, I've found the problem. So apparently the test build I was running was still at version 5, and the `warningTaskFilters` I specified was yet on a different branch. So it must've been the late hour getting me confused. With version 6 it is working as I expect it to be. Much thanks for your support.
