### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mjvk** [MicrosoftPremier/VstsExtensions#78]
With the new versions I got a message saying bqc now requires:

- Build (read)
- Test management (read)
- Code (read and write)
- Code (status)

Is this really required? Especially code read/write I’m not sure if that is possible to accept by the entire company.

**Comment by ReneSchumacher** [comment]
Hey,

I fully understand your concern. Unfortunately, the two code scopes are needed to post pull request statuses and comments. Thus, the extension does not properly work without those permissions.

If you want to inspect the extension code, please send us an email to PsGerExtSupport@microsoft.com so we can send back a copy. We're already working on publishing the code on GitHub so you can do reviews whenever needed.

Thanks,
René

**Comment by ReneSchumacher** [comment]
I updated our change notes to make this change clearer.

**Comment by mjvk** [comment]
Hmm and how are security risks for this? I am not worried about Microsoft stealing are stuff or something. The worry would be more about potential attackers/bugs. Especially the ability to write and delete source code might be a bit iffy. Metadata and such is less of an issue. Too bad there is not more granularity in the permissions.

**Comment by ReneSchumacher** [comment]
You can manage the risk pretty well. There are two security contexts for a build task:
1. The context in which a task is executed.
2. The [build authorization scope](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#build-job-authorization-scope) that you configure in your pipeline definition.

The first is defined by the account running the agent service. If you set up your private build agent correctly or if you use our hosted agents, this account does not have access to Azure DevOps at all. Thus, a task cannot simply open a network connection back to Azure DevOps and grab data unless it has specific credentials to do so. These can either be a _Personal Access Token_ or _Service Connection_ that you'd have to explicitly provide, or the task can ask for the build's OAuth token, which moves it into the second security context.

Script tasks that want to access the build's OAuth token need to have an [explicit permission](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops#allow-scripts-to-access-the-oauth-token) for that. All packaged tasks (like our _Build Quality Checks_ task) can use the _Azure Pipelines Task Library_ to acquire this security token to connect back to Azure DevOps.

In both cases, though, the ability to access data in Azure DevOps is still governed by the permission system. **By default, a build's OAuth token only has read permissions on source code and cannot change or delete anything, even if the extension has the _vso.code_write_ security scope.** That is why we put an explicit note about the necessary security settings into our [documentation](https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md#pull-request-status).

I hope that helps with the decision whether or not to accept the scope change. Let me know if you need anything else.

René

**Comment by mjvk** [comment]
Wow great answer! Thank you, very clear and acceptable now.

**Comment by ReneSchumacher** [comment]
Thanks! I'll keep the issue pinned and change the title a bit so that other people with security concerns can find it.
