### ISSUE TITLE
##[error]Cannot read property 'referenceName' of null

### ISSUE THREAD

**Issue by pswetz** [MicrosoftPremier/VstsExtensions#83]
Getting this no matter what settings I use. Can anyone assist?

**Comment by pswetz** [comment]
I have managed to avoid the issue now but a better error message that says what field is causing the issue would be helpful.

**Comment by ReneSchumacher** [comment]
Hi @pswetz,

what task are you using and when does the error occur? We cannot add a more useful error message unless we know where the error comes from :)

Thanks
René
