### ISSUE TITLE
Extensions is not available

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftPremier/VstsExtensions#85]
Hi guys, I just installed your extension "Create Work Item", but it is not available for any opertaions:
![image](https://user-images.githubusercontent.com/12109173/77431635-044caf80-6dee-11ea-9339-d58466e9ddf2.png)

I already done:
1. Reopen release pipeline.

Help me figure out how to use it please.

**Comment by woehrl01** [comment]
Hi @VerdonTrigance ,

please try a full logout/login circle for Azure Devops. This should mitigate your issue. 

Best
Lukas

**Comment by VerdonTrigance** [comment]
> Hi @VerdonTrigance ,
> 
> please try a full logout/login circle for Azure Devops. This should mitigate your issue.
> 
> Best
> Lukas

Still same. It's not available. Same picture.

**Comment by ReneSchumacher** [comment]
Hi @VerdonTrigance,

can you tell me where you installed the extension? I assume you installed in an Azure DevOps organization, right? Did you install additional extensions from us (Build Quality Checks, Post Build Cleanup)?

If you installed on Azure DevOps, could you please open the following URL in your browser and send us the resulting JSON via email to PSGerExtSupport@microsoft.com:

https://extmgmt.dev.azure.com/{organization)/_apis/extensionmanagement/installedextensionsbyname/mspremier/BuildQualityChecks

Please replace the {organization} placeholder with the name of your org.

Thanks,
René

**Comment by VerdonTrigance** [comment]
> Hi @VerdonTrigance,
> 
> can you tell me where you installed the extension? I assume you installed in an Azure DevOps organization, right? Did you install additional extensions from us (Build Quality Checks, Post Build Cleanup)?
> 
> If you installed on Azure DevOps, could you please open the following URL in your browser and send us the resulting JSON via email to [PSGerExtSupport@microsoft.com](mailto:PSGerExtSupport@microsoft.com):
> 
> [https://extmgmt.dev.azure.com/{organization)/_apis/extensionmanagement/installedextensionsbyname/mspremier/BuildQualityChecks](https://extmgmt.dev.azure.com/%7Borganization)/_apis/extensionmanagement/installedextensionsbyname/mspremier/BuildQualityChecks)
> 
> Please replace the {organization} placeholder with the name of your org.
> 
> Thanks,
> René

I'm not sure what is {organization} is. Is it 'something' from https://something.visualstudio.com ?

**Comment by ReneSchumacher** [comment]
Hey,

sorry for not being more precise and yes, the organization is the name of your Azure DevOps Services "account". Depending on your org settings this is ether https://{organization}.visualstudio.com or https://dev.azure.com/{organization}.

**Comment by VerdonTrigance** [comment]
> Hey,
> 
> sorry for not being more precise and yes, the organization is the name of your Azure DevOps Services "account". Depending on your org settings this is ether https://{organization}.visualstudio.com or [https://dev.azure.com/{organization}](https://dev.azure.com/%7Borganization%7D).

Response is: 
`{"$id":"1","innerException":null,"message":"TF1590003: No app with id mspremier.BuildQualityChecks is installed in this organization.","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.InstalledExtensionNotFoundException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"InstalledExtensionNotFoundException","errorCode":0,"eventId":3000}`

**Comment by ReneSchumacher** [comment]
Oh, sorry, I copied the wrong extension name (however, that answers the question if you have installed the BQC task as well). Please replace the name BuildQualityChecks with CreateWorkItem.

**Comment by VerdonTrigance** [comment]
`{"extensionId":"CreateWorkItem","extensionName":"Create Work Item","publisherId":"mspremier","publisherName":"Microsoft Premier Services","version":"1.5.5","registrationId":"0e2d0cb3-ab15-48c2-a41e-736c9c86ad2c","manifestVersion":1.0,"baseUri":"https://mspremier.gallerycdn.vsassets.io/extensions/mspremier/createworkitem/1.5.5/1578919628636","fallbackBaseUri":"https://mspremier.gallery.vsassets.io/_apis/public/gallery/publisher/mspremier/extension/CreateWorkItem/1.5.5/assetbyname","scopes":["vso.work_write","vso.project"],"contributions":[{"id":"mspremier.CreateWorkItem.WorkItemTypePicker","type":"ms.vss-distributed-task.task-input-editor","targets":["ms.vss-distributed-task.task-input-editors"],"properties":{"name":"Work Item Type Picker","uri":"WorkItemTypePicker/static/WorkItemTypePicker.html","::Attributes":16,"::Version":"1.5.5"},"constraints":[{"name":"ExtensionLicensed","properties":{"extensionId":"mspremier.CreateWorkItem"}}],"restrictedTo":["member"]},{"id":"mspremier.CreateWorkItem.ClassificationNodePicker","type":"ms.vss-distributed-task.task-input-editor","targets":["ms.vss-distributed-task.task-input-editors"],"properties":{"name":"Classification Node Picker","uri":"ClassificationNodePicker/static/ClassificationNodePicker.html","::Attributes":16,"::Version":"1.5.5"},"constraints":[{"name":"ExtensionLicensed","properties":{"extensionId":"mspremier.CreateWorkItem"}}],"restrictedTo":["member"]},{"id":"mspremier.CreateWorkItem.FieldMappingHelper","type":"ms.vss-distributed-task.task-input-editor","targets":["ms.vss-distributed-task.task-input-editors"],"properties":{"name":"Field Mapping Helper","uri":"FieldMappingHelper/static/FieldMappingHelper.html","::Attributes":16,"::Version":"1.5.5"},"constraints":[{"name":"ExtensionLicensed","properties":{"extensionId":"mspremier.CreateWorkItem"}}],"restrictedTo":["member"]},{"id":"mspremier.CreateWorkItem.CreateWorkItem-task","type":"ms.vss-distributed-task.task","targets":["ms.vss-distributed-task.tasks"],"properties":{"name":"Task","::Attributes":16,"::Version":"1.5.5"},"constraints":[{"name":"ExtensionLicensed","properties":{"extensionId":"mspremier.CreateWorkItem"}}],"restrictedTo":["member"]}],"installState":{"flags":"none","lastUpdated":"2020-03-24T13:33:01.3Z"},"contributionTypes":[],"lastPublished":"2020-01-13T12:47:08.63Z","files":[],"demands":["api-version/3.0"]}`

**Comment by ReneSchumacher** [comment]
Thanks for the result. This looks all good so the extension should be installed correctly. Are you still unable to select the task from the task list? If so, could you try uninstalling and reinstalling the extension? We had similar problems in the past and they were related to a slow backend process in Azure DevOps Services. However, tasks showed up properly after about 15 to 20 minutes.

If the task does not become available after you reinstall the extension, please let me know so I can work with the Azure DevOps teams to figure out what is going wrong. In that case, please send me the name of your organization via email to PSGerExtSupport@microsoft.com so the product teams can take a look.

**Comment by VerdonTrigance** [comment]
> Thanks for the result. This looks all good so the extension should be installed correctly. Are you still unable to select the task from the task list? If so, could you try uninstalling and reinstalling the extension? We had similar problems in the past and they were related to a slow backend process in Azure DevOps Services. However, tasks showed up properly after about 15 to 20 minutes.
> 
> If the task does not become available after you reinstall the extension, please let me know so I can work with the Azure DevOps teams to figure out what is going wrong. In that case, please send me the name of your organization via email to [PSGerExtSupport@microsoft.com](mailto:PSGerExtSupport@microsoft.com) so the product teams can take a look.

Problem is still there. I wrote a message. Please check.

**Comment by ReneSchumacher** [comment]
Hi @VerdonTrigance,

I just checked the internal ticket for your issue and realized that is was resolved. Since the issue seems to be gone, I'm closing it now. If you need anything else, feel free to add additional comments or open a new issue.

Thanks and happy building!
René

**Comment by VerdonTrigance** [comment]
Yes, thank you for helping. I thought it was agentless task, but it should run at some of them.
