### ISSUE TITLE
Build Quality Check :: using a variable baseline/repository

### ISSUE THREAD

**Issue by Jittery** [MicrosoftPremier/VstsExtensions#86]
Is it possible to use something like $(ProjectName) as the build definition / repository?

i.e. is it possible to supply _baseDefinitionId_, _baseRepoId_ based on a task group variable

**Comment by ReneSchumacher** [comment]
Hey,

I've never really tested this but I believe variables should be replaced by the agent automatically. Thus, if you know the correct values, it should be possible. I'll try to set this up in a test environment tomorrow and let you know.

**Comment by ReneSchumacher** [comment]
Hi again,

I just tested this and can confirm that it works. You just have to make sure that you're using the correct values. The task needs the build definition ID, the repository ID, and the branch ref, even though the UI editor shows the definition name and repository name.

Let me know if it works for you.

René
