### ISSUE TITLE
No PR status posted

### ISSUE THREAD

**Issue by jrperron88** [MicrosoftPremier/VstsExtensions#88]
I'm trying to implement this in my build YAML.

ADO hosted agent is pulling 6.3.0, i'm not sure if this was supported before 6.4.0 but I think it was. I can't find any status in my branch policies that this has posted.

YAML:

     - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@6
        displayName: 'Check build quality'
        inputs:
          showStatistics: true
          checkCoverage: true
          coverageFailOption: fixed
          coverageType: branches
          explicitFilter: false
          coverageThreshold: $(coverageThreshold)

I have granted the Project Build Service (corp) account Contribute/Contribute to pull requests access for the repo we are building against.

I see the extensions in the build that the coverage passed, but nothing in the PR status, or a branch policy that I can add

**Comment by ReneSchumacher** [comment]
Hi @jrperron88,

PR status policies were introduced in v6.4.1 (see https://github.com/MicrosoftPremier/VstsExtensions/blob/master/BuildQualityChecks/en-US/changeNotes.md#641). Please update the extension. The update should need approval as we changed the security scopes of the extension. We now don't require any security scope, but even this change needs to be approved by one of your AzDO org administrators.

Please let me know if this resolves your issue.

René

**Comment by jrperron88** [comment]
Thanks @ReneSchumacher ! Since we are using a unbuntu Azure hosted agent, how would I update the extensions? The YAML is automatically pulling down 6.3.0, and I don't think there is a way to give it anything other than a major version number

**Comment by ReneSchumacher** [comment]
You need to go to extensions inside your organization settings (https://dev.azure.com/{organization}/_settings/extensions). At the top you should see an entry for the Build Quality Checks extension marked as "needs your attention". Just click on it and approve the update. Once that is done, v6.4.4 should be automatically installed into your organization. After that, the agents will start pulling v6.4.4 instead of v6.3.0.

**Comment by jrperron88** [comment]
@ReneSchumacher That was it, and it is now working perfectly. Thank you!
