### ISSUE TITLE
dotnet core build task warnings not caught

### ISSUE THREAD

**Issue by bdn-mca** [MicrosoftPremier/VstsExtensions#98]
We are using "dotnet core build" step with fxcop analyzers for code analysis. Since we introduced the fxcop analyzers at a later stage, we had around 1000 warnings suppressed in a global suppression file, and agreed to have 0 warnings from this point on.

In the CI, "Check build quality" always reports 0 warnings, even if the dotnet build step beforehand reports a warning.
Warning threshold is set to 0, and dotnet is added to task filters (as you can see from the task output)
Now, I read about the workaround of using MSBuild instead of dotnet build. However, MSBuild does not take global suppressions files into account, and reports 1000 warnings - and "Check build quality" duly fails the build in that case.

Any advice?

![image](https://user-images.githubusercontent.com/8034948/83527532-36624800-a4e8-11ea-8d93-8e29e35b7713.png)

![image](https://user-images.githubusercontent.com/8034948/83527584-45e19100-a4e8-11ea-81dd-27b42eb63eeb.png)

**Comment by woehrl01** [comment]
Hi! 

This probably sounds like a configuration related issue. Could you please send us the log of the specific build to psgerextsupport@microsoft.com, so we can have a deeper look into the applied configuration?

Best

**Comment by bdn-mca** [comment]
The issue is with the dotnet build task - it does not report the warnings in the build summary, and "Check build quality" cannot catch any warnings.
It will be like this until an update is applied, as per [this](https://github.com/Microsoft/azure-pipelines-tasks/issues/7749#issuecomment-598897092) comment.

As a workaround, adding "Warning Filters (Tasks)" in the "Check build quality" task fails the build if there are warnings over the threshold:
/\s([1-9]\d*\.?[0]*)\s+Warning\(s\)|\s([1-9]\d*\.?[0]*)\s+Error\(s\)/
