### ISSUE TITLE
Code Quality reporting coverage decrease erroneously 

### ISSUE THREAD

**Issue by hisuwh** [MicrosoftPremier/VstsExtensions#99]
The Code quality check is reporting a branch coverage decrease from 32.2288% (4260 branches) to 29.9064% (3034).

However, this is after I have ran a build with `BQC.ForceNewBaseline=true` which passed with a code coverage output of 29.8% (3032).

So where is it getting this 32.2288% from and how do I make it work correctly?

**Comment by ReneSchumacher** [comment]
Hi Henry,

without more log information I cannot be sure where the task got the wrong coverage value from. Did the build you ran with BQC.ForceNewBaseline=true succeed? If so, can you send me the log file for that build and the one that incorrectly failed with the coverage decrease to PSGerExtSupport@Microsoft.com? I'll take a look at the logs and get back to you with more information.

René

**Comment by ReneSchumacher** [comment]
Hi @hisuwh,

we haven't received any additional information from you. Did you resolve the issue yourself or do you still need assistance?

René

**Comment by ReneSchumacher** [comment]
Hi @hisuwh,

since we didn't receive any feedback within the last two weeks, I'm closing the issue. If the problem still persists, please feel free to contact us again.

René
